import pandas as pd

# Examine cohort seed data
print("="*80)
print("COHORT SEED DATA")
print("="*80)
cohort_df = pd.read_csv('data/seed_data01/cohort_AR_data_mock_A.csv')
print(f"Rows: {len(cohort_df)}")
print(f"Columns: {list(cohort_df.columns)}")
print("\nFirst 5 rows:")
print(cohort_df.head())
print("\nData types:")
print(cohort_df.dtypes)

print("\n" + "="*80)
print("COURSE SEED DATA")
print("="*80)
course_df = pd.read_csv('data/seed_data01/course_AR_data_mock.csv')
print(f"Rows: {len(course_df)}")
print(f"Columns: {list(course_df.columns)}")
print("\nFirst 5 rows:")
print(course_df.head())
print("\nData types:")
print(course_df.dtypes)

print("\n" + "="*80)
print("FINANCIAL AID SEED DATA")
print("="*80)
financial_df = pd.read_excel('data/seed_data01/financialaid_analysis_ready_file_template.xlsx')
print(f"Rows: {len(financial_df)}")
print(f"Columns: {list(financial_df.columns)}")
print("\nFirst 5 rows:")
print(financial_df.head())
print("\nData types:")
print(financial_df.dtypes)
